# Generated by Django 4.1.5 on 2023-01-31 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0003_alter_task_options_rename_creation_date_task_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(
                default="general", related_name="tasks", to="todo.tag"
            ),
        ),
    ]
