# Generated by Django 4.1.5 on 2023-01-31 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0004_alter_task_status_alter_task_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
