# Generated by Django 4.1.5 on 2023-01-31 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0005_alter_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
