# Generated by Django 4.1.5 on 2023-01-31 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0006_alter_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(related_name="tasks", to="todo.tag"),
        ),
    ]
