# Generated by Django 4.1.5 on 2023-01-31 20:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0007_alter_task_created_alter_task_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(null=True),
        ),
    ]
