# Generated by Django 4.1.5 on 2023-01-31 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0008_alter_task_created_alter_task_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
